### ISSUE TITLE
BLE driver issues

### ISSUE THREAD

**Issue by AuspeXeu** [tijmenvangulik/ErgometerJS#13]
I am having a lot of issues with the BLE driver it seems. After connecting I get this log message a lot `NotSupportedError: GATT operation failed for unknown reason.` After a while it will transmit partial data from the PM5. However not everything there should be and I also get tons of this logged. `wrong csafe frame ending.`

Any thoughts how to zero in on this bug?

It seems like this might be related: https://bugs.chromium.org/p/chromium/issues/detail?id=664863

**Comment by tijmenvangulik** [comment]
You have to give me some more information on what you are exactly doing (which example/platform/ways of connecting/hardware, etc..) Normally it is because of one of the internal drivers is not correctly installed.

Tijmen

**Comment by AuspeXeu** [comment]
I am trying to use the BLE driver on the web. Hardware is my computer which has bluetooth and I am doing that inside chrome.

**Comment by tijmenvangulik** [comment]
What kind of computer mac/pc , version os? version chrome?

**Comment by AuspeXeu** [comment]
Windows 10, latest chrome.

**Comment by tijmenvangulik** [comment]
If you start ergometer-space.org <http://ergometer-space.org/> on your machine? Does it work? (uses the same version of ergometerjs as I last published )

**Comment by tijmenvangulik** [comment]
There are some requirements for using web blue tooth. For example if it is not local host you must use https.

**Comment by AuspeXeu** [comment]
It's localhost. Ergometer-space.org has the same issues it seems.

**Comment by tijmenvangulik** [comment]
if ergometer-space.org <http://ergometer-space.org/> does not work, there must be some thing with windows or your ergometer. Do you have the latest version of windows 10 (the first versions of windows 10 had limited blue tooth drivers, chrome depends on the latest) and the PM5 monitor firmware (older version can be buggy).

**Comment by AuspeXeu** [comment]
Well ... according to the link, in case you haven't had a chance to look at it. It can cause issues if the `startNotifications` commands are called in parallel instead of in sequence. And I checked your code, you're doing them all at once.

**Comment by tijmenvangulik** [comment]
I have seen that problem before, on android, On android the driver now schedules every thing after each other. This may be also a problem of the blue tooth  hardware.  In the utilities there is a routine promiseAllSync , in the past I used this to work around this problem, but it was not needed any more (and it slows down the init). 
I am interested if you replace the Promise.all with the promiseAllSync, if your problem is then fixed. Maybe we have to set it back

Tijmen

**Comment by AuspeXeu** [comment]
Well, your `promiseAllSync` does not actually serialize the execution of the promises. they are just awaited in a different way. The execution is started upon `new Promise` which is before the `promiseAllSync` call.

**Comment by tijmenvangulik** [comment]
I am currently very busy with making the a team version of ergometer-space. Can you make a better solution?

Tijmen

**Comment by tijmenvangulik** [comment]
I have just checked the function. As fare as I know, promises are created directly executed later. And code in the “then" is executed after the other promise. This is exactly what this function does do executes the next promise in the array using the “then”. So this should work or there is some thing else which is going wrong and we are searching in the wrong direction..

**Comment by AuspeXeu** [comment]
This is not correct. The promise code starts executing immediately after the promise is instantiated. The `then` code simply means this is called after the promise finished. I have a small fix in my version right now which I'll be trying out today and see if it helps.

**Comment by AuspeXeu** [comment]
Yeah, so this still seems unresolved for me. I tried to run this on my Android phone. and am getting these weird GATT errors.

**Comment by tijmenvangulik** [comment]
Now you have these problems on two devices. Just to be sure do you also have these problems if you run ergometer-space on your phone. Ergometer space is used by many users without problem. I have only one report of a user which has problems on an old  phone which he can not upgrade. If the same version of ergometer-space does not work on both the vices (pc and phone) then it is more likely that it has some thing todo with your PM5. What is the version info hardware/software of your PM5?.

**Comment by AuspeXeu** [comment]
It is a fairly old phone. You have the latest version from the git repo running on your erg space, no?

**Comment by tijmenvangulik** [comment]
It is a app which you can install from the app store

https://play.google.com/store/apps/details?id=org.tijmenvangulik.ergometerspace&hl=en <https://play.google.com/store/apps/details?id=org.tijmenvangulik.ergometerspace&hl=en>

**Comment by tijmenvangulik** [comment]
I could for the first time repeat the connection problems. Hopefully I can now debug and fix this.

**Comment by tijmenvangulik** [comment]
I have published a fix for multi plex mode for android. You can turn on this mode and then it should compensate for limited blue tooth hard ware.

**Comment by AuspeXeu** [comment]
Thanks
