### ISSUE TITLE
Ionic 1 demo

### ISSUE THREAD

**Issue by remisture** [tijmenvangulik/ErgometerJS#3]
It would be nice to have a demo for Ionic 1 as well. Do you plan on making one?

**Comment by tijmenvangulik** [comment]
I am not planning to add a not Ionic 1 because it is going to be replace by ionic 2 soon. (and version 2 is so much better)  I want to spent my time on examples of other frame works like react. But if any one adds an example of ionic 2 I will add it to the repository.
