### ISSUE TITLE
WebBluetooth messages stop after a view seconds

### ISSUE THREAD

**Issue by beaufortfrancois** [tijmenvangulik/ErgometerJS#4]
Hey @tijmenvangulik,

Can you let us know if latest Chrome canary fixed your issue at https://bugs.chromium.org/p/chromium/issues/detail?id=681309?

**Comment by tijmenvangulik** [comment]
Thanks, 
Yes I will test it

**Comment by tijmenvangulik** [comment]
Just tested it with the latest chrome canary , I get I nice blue tooth icon in the tab, but the problem is still the same, after some time I do not get messages from the device. I hope I can get some more debug information with the new canary.

**Comment by beaufortfrancois** [comment]
Thanks @tijmenvangulik!
I've added your comment at https://bugs.chromium.org/p/chromium/issues/detail?id=681309#c17
Hopefully, [upcoming patch](https://codereview.chromium.org/2745983003/) will give us more details on what is happening. I'll ping you for sure when this one lands ;)

**Comment by beaufortfrancois** [comment]
Hey Tijmen, now that https://codereview.chromium.org/2745983003 has landed, do you mind trying the latest chrome canary and share your logs there?

See how to by reading https://www.chromium.org/developers/how-tos/file-web-bluetooth-bugs

**Comment by tijmenvangulik** [comment]
I hope that i Will find this weekend Some time to post the debug logs

Tijmen

**Comment by tijmenvangulik** [comment]
I have added an log to the issue (comment 19)

https://bugs.chromium.org/p/chromium/issues/detail?id=681309&can=2&start=0&num=100&q=&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified&groupby=&sort=

**Comment by beaufortfrancois** [comment]
Thank you!
See my reply at https://bugs.chromium.org/p/chromium/issues/detail?id=681309#c20

**Comment by tijmenvangulik** [comment]
made workaround
