### ISSUE TITLE
PM3?

### ISSUE THREAD

**Issue by tomazbracic** [tijmenvangulik/ErgometerJS#5]
Hi,

will this work with PM3? You are mentioning just PM5.

**Comment by tijmenvangulik** [comment]
The pm3 does not have Bluetooth. Only the pm5 supports Bluetooth. On my ergometer-space.org website i use a data sever to connect to older Pm. But i assume that modern users want to connect using Bluetooth and a phone. So older Pm Will be obsolete soon. It is possible to upgrade the pm
