### ISSUE TITLE
Issue with Bluetooth Device filtering

### ISSUE THREAD

**Issue by copat** [tijmenvangulik/ErgometerJS#6]
Hi, nice work! There is an issue with the filtering for requestDevice. It seems to be related to what services are published when the device is already paired.

```
navigator.bluetooth.requestDevice({
                            filters: [
                                { services: [ble.PMDEVICE]
                                }
                            ],
                            optionalServices: [ble.PMDEVICE_INFO_SERVICE, ble.PMCONTROL_SERVICE, ble.PMROWING_SERVICE]

ble.PMDEVICE = "ce060000-43e5-11e4-916c-0800200c9a66";
ble.PMDEVICE_INFO_SERVICE = "ce060010-43e5-11e4-916c-0800200c9a66";
ble.PMCONTROL_SERVICE = "ce060020-43e5-11e4-916c-0800200c9a66";
ble.PMROWING_SERVICE = "ce060030-43e5-11e4-916c-0800200c9a66";
```

The PMDEVICE service may not be available and thus no device is found. Changing the filter to `namePrefix : "PM5 "` allows the device to be found every time. Filtering on PMDEVICE_INFO_SERVICE instead may also be an option. This was tested on Chrome OS 66.

**Comment by tijmenvangulik** [comment]
Thanks I will look into this problem

**Comment by copat** [comment]
Thanks! Another theory is that it is somehow related to how you are supposed to reconnect to devices. Although it has nothing to do with the actual rowing services, this example is very stable when it comes to maintaining the bluetooth connection with the PM5, and also disconnecting/reconnecting: https://googlechrome.github.io/samples/web-bluetooth/device-disconnect.html?namePrefix=PM5

**Comment by copat** [comment]
I have been looking at the issue using nRF Connect and it is more likely related to a specific handling by Chrome/ChromeOS, rather than the actual service broadcast.
