### ISSUE TITLE
Node JS Demo?

### ISSUE THREAD

**Issue by skatpgusskat** [tijmenvangulik/ErgometerJS#7]
Hello.

Can you let me know how to run any demo with node js? I read that this project also make nodeJS version for linux, (including Raspberry pi <<- which one I need!! ) please?

**Comment by tijmenvangulik** [comment]
I think the most restricted part which determine the version is the noble -   compatibility layer

https://github.com/noble/noble/wiki/Getting-started

I have no experience in getting this to work but I see no reason why it shouldn’t with maybe some small fixes.

Another question for you, why node? Do you really need server site ergometer data? Where is your GUI running? You can connect straight from the browser to the ergometer using web blue thooth. This way you can skipp the whole server part.

You could even install an chrome browser on the raspberry-pi 

https://tutorials-raspberrypi.com/google-chrome-for-raspberry-pi/ <https://tutorials-raspberrypi.com/google-chrome-for-raspberry-pi/>

As test if it works you can start https://ergometer-space.org  on a rasberry-pi and see if you can connect to your ergometer. If you want it to be a bit more native you can combine node and chrome using electron. (Also working on a rasberry pi)

Tijmen

**Comment by dgramop** [comment]
What about for USB over node?

**Comment by tijmenvangulik** [comment]
do you mean node-hid? This works fine. Very stable and professional drivers. Also works in electron.I do not have experience with normal usb only hid usb. 

Tijmen
